//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int ID { get; set; }
        public Nullable<int> CpuValue { get; set; }
        public Nullable<int> MemValue { get; set; }
        public Nullable<System.DateTime> SampleDate { get; set; }
    }
}
