USE [master]
GO

/****** Object:  Database [MonitorServiceDB]    Script Date: 7/8/2019 12:06:38 PM ******/
CREATE DATABASE [MonitorServiceDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MonitorServiceDB', FILENAME = N'C:\Users\Marcos\MonitorServiceDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MonitorServiceDB_log', FILENAME = N'C:\Users\Marcos\MonitorServiceDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MonitorServiceDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MonitorServiceDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MonitorServiceDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MonitorServiceDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MonitorServiceDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MonitorServiceDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MonitorServiceDB] SET  MULTI_USER 
GO

ALTER DATABASE [MonitorServiceDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MonitorServiceDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MonitorServiceDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MonitorServiceDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MonitorServiceDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MonitorServiceDB] SET QUERY_STORE = OFF
GO

USE [MonitorServiceDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [MonitorServiceDB] SET  READ_WRITE 
GO


